export type Gender = 'male' | 'female' | 'neutral';

const GENDER_MAP: ReadonlyMap<string, Gender> = new Map([
  // Female
  ['ענת', 'female'],
  ['אביבה', 'female'],
  ['בר', 'female'],
  ['כרמל', 'female'],
  ['קרולין', 'female'],
  ['דפנה', 'female'],
  ['דנה', 'female'],
  ['אפרת', 'female'],
  ['גיל', 'female'],
  ['הדר', 'female'],
  ['הגר', 'female'],
  ['חן', 'female'],
  ['ענבל', 'female'],
  ['קרין', 'female'],
  ['לורה', 'female'],
  ['ליעד', 'female'],
  ['לילך', 'female'],
  ['ליאור', 'female'],
  ['מאיה', 'female'],
  ['מיכל', 'female'],
  ['מילה', 'female'],
  ['נועה', 'female'],
  ['נופר', 'female'],
  ['נוי', 'female'],
  ['אולגה', 'female'],
  ['ראות', 'female'],
  ['רון', 'female'],
  ['סיפן', 'female'],
  ['שחר', 'female'],
  ['שהר', 'female'],
  ['שיר', 'female'],
  ['סיון', 'female'],
  ['טליה', 'female'],
  ['טום', 'female'],
  ['טובה', 'female'],
  ['צופית', 'female'],
  ['ולנה', 'female'],
  ['ורד', 'female'],
  ['יעל', 'female'],
  ['ירדן', 'female'],
  ['זנטה', 'female'],
  ['אבגר', 'female'],

  // Male
  ['אמית', 'male'],
  ['אמנון', 'male'],
  ['בוריס', 'male'],
  ['דניאל', 'male'],
  ['דולב', 'male'],
  ['דור', 'male'],
  ['אתאי', 'male'],
  ['עדן', 'male'],
  ['גל', 'male'],
  ['גיא', 'male'],
  ['ישראל', 'male'],
  ['חקובו', 'male'],
  ['מאוז', 'male'],
  ['מתן', 'male'],
  ['מתיו', 'male'],
  ['נדב', 'male'],
  ['נתנאל', 'male'],
  ['ניר', 'male'],
  ['ניסן', 'male'],
  ['אוהד', 'male'],
  ['עומר', 'male'],
  ['עומרי', 'male'],
  ['אורי', 'male'],
  ['רועי', 'male'],
  ['רואי', 'male'],
  ['רוי', 'male'],
  ['שקד', 'male'],
  ['שלו', 'male'],
  ['שי', 'male'],
  ['תמיר', 'male'],
  ['תומר', 'male'],
  ['יעקב', 'male'],
  ['קובי', 'male'],
  ['יניב', 'male'],
  ['יונתן', 'male'],
  ['עידן', 'male'],
  ['איגור', 'male'],
  ['איתי', 'male'],
  ['מקסים', 'male'],
  ['סטס', 'male'],
  ['גבין', 'male'],

  // Neutral (ambiguous)
  ['אור', 'neutral'],
  ['לידור', 'neutral'],
  ['טל', 'neutral'],
]);

export function resolveGender(name: string): Gender {
  return GENDER_MAP.get(name.trim()) ?? 'neutral';
}
